### ISSUE TITLE
Probably a typo in [netlify.toml] configuration related to [plugin.inputs]

### ISSUE THREAD

**Issue by jvlad** [netlify-templates/astro-toolbox#136]
https://github.com/netlify-templates/astro-toolbox/blob/052d0bc5e499f9d928ce20158dfc2eb4ee6413b9/netlify.toml#L16

Shouldn't it be  
[plugin**s**.inputs]   
instead?

**Comment by TomasBankauskas** [comment]
Thank you for noticing, @jvlad. Fixed.
