### ISSUE TITLE
Problem with functions redirect(?)

### ISSUE THREAD

**Issue by duktiga-havet** [netlify-templates/astro-toolbox#35]
Hi!

Running netlify dev and navigating to http://localhost:3000/api/joke I get:

```
404: Not found
Path: /api/joke
```

When I built the project with pnpm, which upgraded allt the packages, I aw that netlify dev outputted the following error message:

```
wasm streaming compile failed: TypeError: Failed to parse URL from /usr/local/Cellar/netlify-cli/10.3.0/libexec/lib/node_modules/netlify-cli/node_modules/netlify-redirector/lib/redirects.wasm
```

Building with npm I didn't get that error message. 

I have verified that the joke function is available on:

```
http://localhost:55064/.netlify/functions/joke
```

**55064** is the port that netlify dev outputted here: (which seems to be dynamic, changing on each run)

```
◈ Loaded function joke http://localhost:8888/.netlify/functions/joke
◈ Functions server is listening on 55064
``` 

I note that port **8888** did not work, despite being in the url outputted by netlify dev

Tried node 16.16 and 18.6, npm and pnpm with the same result. 

Full netlify dev output

```
◈ Netlify Dev ◈
◈ Injected build settings env var: STORYBLOK_TOKEN
◈ Ignored general context env var: LANG (defined in process)
◈ Loaded function joke http://localhost:8888/.netlify/functions/joke.
◈ Functions server is listening on 55705
◈ Starting Netlify Dev with Astro

> @example/basics@0.0.1 dev
> astro dev

  🚀  astro  v1.0.0-beta.73 started in 200ms
  
  ┃ Local    http://localhost:3000/
  ┃ Network  use --host to expose
  
  ▶ This is a  beta  prerelease build
    Feedback? https://astro.build/issues
    
```

**Comment by maxcell** [comment]
Howdy @duktiga-havet! That's super weird!! What version of `netlify-cli` were you using? Everything else seems like it was in order. Do you have a repository for me to take a gander at as well?

**Comment by duktiga-havet** [comment]
@maxcell It was just a clone of this repo but I think the error I made was accidentally upgrading a bunch of packages by with pnpm and maybe had an unlucky interaction there. When I pulled down the newest version of the repo now everything worked fine with both npm and pnpm. Thanks for checking in!

**Comment by aminnez** [comment]
I have the same issue.
I think the Astro routing system (Astro netlify integration) ignores the redirect section of netlify.toml config.
I looked at the dist/_redirects file that Astro generates automatically, and there is no imported line from the Netlify config file.
Any suggestion?
